update solution

diff --git a/bin/solvepart1forme b/bin/solvepart1forme
--- a/bin/solvepart1forme
+++ b/bin/solvepart1forme
@@ -15,14 +15,18 @@
 # limitations under the License.
 
 #create EKS cluster
+echo "####################################"
+echo "We create an EKS cluster in the Spoke VPC now."
 eksctl get clusters app-first-sec &> /dev/null
 if [ $? -eq 0 ]; then
     echo $(eksctl get clusters app-first-sec)
     echo " "
     echo "-----------------------------------------------"
-    echo "EKS Cluster is already provisioned"
+    echo "EKS Cluster is already provisioned!!!"
     echo "-----------------------------------------------"
 else
+    echo "This single command begins a complex process driven through CloudFormation."
+    echo "This will take approximately 25 minutes to complete given the shear number of steps to prepare all of the AWS services."
     eksctl create cluster --config-file $HOME/environment/lab/aws/eks-cluster.yaml
     echo " "
     echo "-----------------------------------------------"
@@ -31,6 +35,8 @@ else
 fi
 
 #Deploy Sock Shop application
+echo "####################################"
+echo "Now, we will deploy the Sock Shop application on the EKS cluster."
 kubectl apply -f $HOME/environment/lab/sock-shop/sock-shop-elb.yaml
 echo " "
 echo "-----------------------------------------------"
@@ -50,12 +56,13 @@ echo "$(ssh -i ~/.ssh/$AWS_KEYPAIR_NAME ubuntu@$AWS_GITLAB_IP 'sudo grep Passwor
 echo "================================"
 echo "Go to link http://$AWS_GITLAB_FQDN/-/profile/personal_access_tokens (Use the credentials above to login)"
 echo "Generate a Private Access Token by adding api and write_repository permissions"
+echo "We need this token to set up the Front End microservice project on your private GitLab Instance."
 echo "Enter the Private Access Token:"
 read GITLAB_TOKEN
 
 #Create the Gitlab project
-res = $(curl --write-out "%{http_code}\n" --header "Private-Token: $GITLAB_TOKEN" -X POST "http://$AWS_GITLAB_FQDN/api/v4/projects?name=Front-End" --output /dev/null --silent)
-if [ $res1 == "200" ]; then
+res=$(curl --write-out "%{http_code}\n" --header "Private-Token: $GITLAB_TOKEN" -X POST "http://$AWS_GITLAB_FQDN/api/v4/projects?name=Front-End" --output /dev/null --silent)
+if [ $res1=="201" ]; then
   echo " "
   echo "----------------------------------"
   echo "Created Gitlab Project - Front-End"
@@ -70,6 +77,7 @@ fi
 echo "####################################"
 echo "Go to link http://$AWS_GITLAB_FQDN/root/Front-End/-/settings/ci_cd"
 echo "Expand the Runners section and copy the registration token"
+echo "We will now register a Runner to your private GitLab instance to run the CI/CD pipeline jobs."
 echo "Enter the Gitlab Runner Registration token:"
 read RUNNER_TOKEN
 
@@ -94,61 +102,79 @@ echo " "
 
 #Add AWS environment variables for pipeline
 echo "####################################"
+echo "Now we need to add some CI/CD variables to be used by CI/CD pipeline jobs."
+echo "Gitlab will use these variable to pushthe new container images to ECR repository and then deploy them to EKS cluster."
 export AWS_ACCESS_KEY=$(grep aws_access_key_id ~/.aws/credentials | awk '{ print $3 }')
 export AWS_SECRET_ACCESS=$(grep aws_secret_access_key ~/.aws/credentials | awk '{ print $3 }')
 
 res1=$(curl --write-out "%{http_code}\n" --request POST  --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "http://$AWS_GITLAB_FQDN/api/v4/projects/2/variables" --form "key=AWS_ACCESS_KEY_ID" --form "value=$AWS_ACCESS_KEY" --output /dev/null --silent)
-if [ $res1 == "200" ]; then
+if [ $res1=="201" ]; then
   echo "Added CI/CD variable - AWS_ACCESS_KEY "
 else
   echo "Failed to add CI/CD variable - AWS_ACCESS_KEY"
+  echo "Failure Code: $res1"
 fi
 
 res2=$(curl --write-out "%{http_code}\n" --request POST  --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "http://$AWS_GITLAB_FQDN/api/v4/projects/2/variables" --form "key=AWS_SECRET_ACCESS_KEY" --form "value=$AWS_SECRET_ACCESS" --output /dev/null --silent)
-if [ $res2 == "200" ]; then
+if [ $res2=="201" ]; then
   echo "Added CI/CD variable - AWS_SECRET_ACCESS"
 else
   echo "Failed to add CI/CD variable - AWS_SECRET_ACCESS"
+  echo "Failure Code: $res2"
 fi
 
 res3=$(curl --write-out "%{http_code}\n" --request POST  --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "http://$AWS_GITLAB_FQDN/api/v4/projects/2/variables" --form "key=AWS_DEFAULT_REGION" --form "value=$AWS_REGION" --output /dev/null --silent)
-if [ $res3 == "200" ]; then
+if [ $res3=="201" ]; then
   echo "Added CI/CD variable - AWS_REGION"
 else
   echo "Failed to add CI/CD variable - AWS_REGION"
+  echo "Failure Code: $res3"
 fi
 
 res4=$(curl --write-out "%{http_code}\n" --request POST  --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "http://$AWS_GITLAB_FQDN/api/v4/projects/2/variables" --form "key=DOCKER_REGISTRY" --form "value=$DOCKER_REGISTRY" --output /dev/null --silent)
-if [ $res4 == "200" ]; then
+if [ $res4=="201" ]; then
   echo "Added CI/CD variable - DOCKER_REGISTRY"
 else
   echo "Failed to add CI/CD variable - DOCKER_REGISTRY"
+  echo "Failure Code: $res4"
 fi
 
 echo " "
 echo "---------------------------------------------------"
 echo "Added the environment variables for CI/CD Pipeline"
-echo "----------------------------------------------------"
+echo "---------------------------------------------------"
 echo " "
 
 #Set up the private Git Client Repo
 echo "####################################"
+echo "We will set up your local repo on cloud9 instance and point it to your private Front End GitLab project"
 cd /home/ec2-user/environment
-git clone https://github.com/amansin0504/front-end.git Sock-Shop-Front-End && cd Sock-Shop-Front-End
-git config --global user.name "Administrator" && git config --global user.email "admin@cloudnativeapp.com"
-git remote rm origin && git remote add origin http://Administrator:$GITLAB_TOKEN@$AWS_GITLAB_FQDN/root/front-end.git
-git push -u origin --all
-echo " "
-echo "---------------------------------------------------------------------"
-echo "Front-End local and remote repo (on private GitLab Instance) created"
-echo "---------------------------------------------------------------------"
-echo " "
+git clone https://github.com/amansin0504/front-end.git Sock-Shop-Front-End
+success=$?
+if [[ $success -eq 0 ]];
+then
+  cd Sock-Shop-Front-End
+  git config --global user.name "Administrator" && git config --global user.email "admin@cloudnativeapp.com"
+  git remote rm origin && git remote add origin http://Administrator:$GITLAB_TOKEN@$AWS_GITLAB_FQDN/root/front-end.git
+  git push -u origin --all
+  echo " "
+  echo "-------------------------------------------------------------------------------"
+  echo "Sock-Shop-Front-End local and remote repo (on private GitLab Instance) created"
+  echo "-------------------------------------------------------------------------------"
+  echo " "
+else
+    echo "Something went wrong with cloning sock shop repo or it already exists!"
+fi
 
 #Add the Sock Shop credentials and displace the access link
 echo "####################################"
-addshopuser
 echo "export SOCK_SHOP_ELB=`kubectl get service front-end -n sock-shop -o json | jq -r '.status.loadBalancer.ingress[0].hostname'`" >> ~/.bashrc_lab ; source ~/.bashrc
+addshopuser > /tmp/addinguser.log
 echo "---------------------------------------------------------------------"
 echo "Sock Shop Access:"
 echo $SOCK_SHOP_ELB
+echo "---------------------------------------------------------------------"
+echo "Sock Shop Credentials:"
+echo "User: $POD_NAME"
+echo "Password: $POD_NAME"
 echo "---------------------------------------------------------------------"
